#==================Spring properties================
server:
  port: 5590
  address: 10.5.225.39

#==================Keycloak properties================
keycloak:
  enabled: true
  #Prod
  realm: idrio_cidadao
  auth-server-url: https://auth.apps.saude.rio/auth
  resource: identidade-rio-api
  credentials:
    secret: cde401bc-f222-4a15-9c36-1336d199374f
  #Homol  
  #realm: identidade-rio
  #auth-server-url: https://auth.stage.sauderio.xyz/auth
  #resource: identidade-rio-api
  #credentials:
  #  secret: cde401bc-f222-4a15-9c36-1336d199374f
  ssl-required: none
  bearer-only: true
  confidential-port: 0
  use-resource-role-mappings: false
  principal-attribute: preferred_username
  cors: true
  security-constraints:
    - auth-roles:
      - User
      security-collections:
      - name: unsecured
        patterns:
        - /v1/user
    - auth-roles: 
      - Admin
      security-collections:
      - name: secured
        patterns:
        - /v1/admin

#==================Spring properties================

spring:
#==================Import properties================
  http:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB      
#==================JMS properties================
  activemq:
    broker-url: tcp://10.5.225.39:61616
    user: admin
    password: password
    #in-memory: true
    #pool: 
    #  enabled: false
    
#==================Parameters properties================

file:
  upload-dir: /home/rverli/Documents/uploads

destination:
   create:
      queue: id.rio.create.user.queue    
   import:
      queue: id.rio.import.queue

#==================Logging Configuration================

logging: 
  level: 
    org:
      springframework: 
        boot:
          autoconfigure:
            logging: INFO
        security: DEBUG
      arun: DEBUG
    root: INFO
    keycloak: TRACE

#==================================
