#==================Spring properties================
server:
  port: 5596
  address: 10.5.225.39

#==================Keycloak properties================
keycloak:
  enabled: true
  ssl-required: external
  bearer-only: true
  #use-resource-role-mappings: true
  #principal-attribute: preferred_username
  #enable-cors: true
  public-client: true
  confidential-port: 0
  #Prod
  realm: idrio_cidadao
  auth-server-url: https://auth.apps.saude.rio/auth
  resource: identidade-rio-api
  credentials:
    secret: cde401bc-f222-4a15-9c36-1336d199374f
  #Homol  
  #realm: identidade-rio
  #auth-server-url: https://auth.stage.sauderio.xyz/auth
  #resource: identidade-rio-api
  #credentials:
  #  secret: cde401bc-f222-4a15-9c36-1336d199374f

#==================Spring properties================

spring:
#==================Import properties================
  http:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 200MB      
#==================JMS properties================
  activemq:
    broker-url: tcp://10.5.225.39:61616
    user: admin
    password: biluteteia123
    #in-memory: true
    #pool: 
    #  enabled: false
    
#==================Parameters properties================

file:
  upload-dir: /home/rverli/Documents/uploads

destination:
   queue:
      create: id.rio.create.user.queue      
      import: id.rio.import.queue

#==================Logging Configuration================

logging: 
  level: 
    org:
      springframework: 
        boot:
          autoconfigure:
            logging: INFO
        security: DEBUG
      arun: DEBUG
    root: INFO
    keycloak: TRACE

#==================================
